# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ed6607e6dced6f2ddc571ddaac04dee2023beb9d8379766e9fac47d7940dd86555c01850546631f96cc7a00b9d40822d9eaf12c010c72df5a41bbf4bc3601f6

test:
  secret_key_base: 7e0c12b4ef459a06a3f57dcd3533b3543b5adca86541dfea910c5e69706aa591a0226a0110e8f645ab5ad8f5dd1c07fb0e3e70d16459126d33c35f272a69095a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
